DROP TABLE IF EXISTS credit_account CASCADE;
DROP TABLE IF EXISTS loan_account CASCADE;
DROP TABLE IF EXISTS basic_account CASCADE;
DROP TABLE IF EXISTS borrowing_account CASCADE;
DROP TABLE IF EXISTS lending_account CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS installment CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS budgets CASCADE;
DROP TABLE IF EXISTS ledger_categories CASCADE;
DROP TABLE IF EXISTS ledgers CASCADE;
DROP TABLE IF EXISTS reimbursement_plan CASCADE;
DROP TABLE IF EXISTS reimbursement_record CASCADE;
DROP TABLE IF EXISTS reimbursement_tx_link CASCADE;
DROP TABLE IF EXISTS installment_payments CASCADE;
DROP TABLE IF EXISTS debt_payments CASCADE;
DROP TABLE IF EXISTS global_categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;



