-- users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL
);

--ledgers table
CREATE TABLE IF NOT EXISTS ledgers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ledger_categories table
CREATE TABLE IF NOT EXISTS ledger_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    parent_id BIGINT,
    type VARCHAR(10) NOT NULL CHECK (type IN ('EXPENSE', 'INCOME')),

    FOREIGN KEY (ledger_id) REFERENCES ledgers(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_id) REFERENCES ledger_categories(id)
);

--accounts table
CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    balance DECIMAL(15,2) DEFAULT 0.00,
    user_id BIGINT NOT NULL,
    included_in_asset BOOLEAN DEFAULT TRUE,
    selectable BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

--transaction table
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(10) NOT NULL CHECK ( type IN ('INCOME','EXPENSE','TRANSFER') ),
    ledger_id BIGINT NOT NULL,
    from_account_id BIGINT,
    to_account_id BIGINT,
    category_id BIGINT,
    amount DECIMAL(15,2) NOT NULL,
    note TEXT,
    transaction_date DATE NOT NULL,
    FOREIGN KEY (ledger_id) REFERENCES ledgers(id) ON DELETE CASCADE,
    FOREIGN KEY (from_account_id) REFERENCES accounts(id) ON DELETE SET NULL,
    FOREIGN KEY (to_account_id) REFERENCES accounts(id) ON DELETE SET NULL,
    FOREIGN KEY (category_id) REFERENCES ledger_categories(id) ON DELETE CASCADE
);

-- budgets table
CREATE TABLE IF NOT EXISTS budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT,
    amount DECIMAL(15,2) NOT NULL,
    period VARCHAR(10) NOT NULL CHECK (period IN ('MONTHLY','YEARLY')),
    ledger_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    FOREIGN KEY (category_id) REFERENCES ledger_categories(id) ON DELETE CASCADE,
    FOREIGN KEY (ledger_id) REFERENCES ledgers(id) ON DELETE CASCADE
);

-- global_categories table
CREATE TABLE IF NOT EXISTS global_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE  NOT NULL,
    parent_id BIGINT,
    type VARCHAR(20) NOT NULL CHECK (type IN ('EXPENSE','INCOME')),
    FOREIGN KEY (parent_id) REFERENCES global_categories(id)
);




